### ISSUE TITLE
Remove last rows

### ISSUE THREAD

**Issue by AcckiyGerman** [AcckiyGerman/tabulator-py#1]
As a user I want to be able to delete some unnecessary rows at the end of table, so I don't need to do it manually.

## Acceptance Criteria 

* [x] pipeline processor can skip rows, counting them from the end.
* [x] the PR is accepted by frictionless-data

## Tasks

* [x] analyze [1h]
* [x] learn tabulator-py docs, run examples [1.5h]
* [x] fork the repo, find and analyse the `skip_rows: n` processor [20m]  
* [x] write tests for `skip_rows: -n` [20m]
* [x] extend the function [20m]
* [x] check all the old and new tests are working [10m]
* [x] update the docs: 'Skip rows' and 'Stream' sections [20m]
* [x] do post-review fixes [20m]
* [x] PR to main repo [20m]
* [ ] fix the PR post-review fixes, if any [0..20m]
Overall [4.5 to 5h]

## Analysis 
We already have the ability to remove few first rows in tabulator-py, so It would be better to extend this function, e.g.
```
tabulator:
      skip_rows: 2   # skip the 2-nd row
      skip_rows: -2  # skip the 2-nd row, counting from the end
      skip_rows: [1, 2, -1, -2]   # etc
```
